-- S1p & Sp1n Laundry app: "Updates" list (order steps and promos shown in the app's bell icon).
-- Safe to run more than once.

CREATE TABLE IF NOT EXISTS public.laundry_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES public.laundry_customers(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT,
  data JSONB DEFAULT '{}'::jsonb,   -- e.g. {"type":"order","orderKey":"req-12"} opens that order
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS laundry_notifications_customer_idx ON public.laundry_notifications (customer_id, created_at DESC);

-- Same setting as the other tables until the security lock (security-enable-rls.sql) is applied
ALTER TABLE public.laundry_notifications DISABLE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload schema';
