-- S1p & Sp1n Laundry app: customer reviews and the Facebook page link.
-- Only creates/changes laundry_* tables. Safe to run more than once.

CREATE TABLE IF NOT EXISTS public.laundry_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id BIGINT REFERENCES public.branches_espresso(id),
  customer_id BIGINT REFERENCES public.laundry_customers(id),
  order_key TEXT NOT NULL,          -- app order id, e.g. ord-123 or req-45
  order_code TEXT,                  -- what the customer sees, e.g. SP-1043
  order_id BIGINT,
  pickup_request_id BIGINT,
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  tags JSONB DEFAULT '[]'::jsonb,
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (customer_id, order_key)
);
ALTER TABLE public.laundry_reviews DISABLE ROW LEVEL SECURITY;

-- Facebook page shown in the app (edit it in Table Editor → laundry_app_settings)
ALTER TABLE public.laundry_app_settings ADD COLUMN IF NOT EXISTS facebook_url TEXT;
UPDATE public.laundry_app_settings
SET facebook_url = 'https://www.facebook.com/profile.php?id=61591057528640'
WHERE branch_id = 27 AND facebook_url IS NULL;

NOTIFY pgrst, 'reload schema';
