-- S1p & Sp1n Laundry app: News feed (posts like a Facebook page: photos, posters, videos, quotes) with likes.
-- Managed from the POS: Laundry App → News feed. Safe to run more than once.

CREATE TABLE IF NOT EXISTS public.laundry_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id BIGINT REFERENCES public.branches_espresso(id),
  kind TEXT NOT NULL DEFAULT 'photo',      -- photo | video | quote
  tag TEXT NOT NULL DEFAULT 'news',        -- news | laundry | coffee | customers | promo
  caption TEXT,                            -- text under the post
  image_ids BIGINT[] DEFAULT '{}',         -- pictures (laundry_media), up to 6
  video_url TEXT,                          -- public video link (Supabase Storage)
  video_path TEXT,                         -- file name in the storage bucket (to delete it later)
  quote_text TEXT,
  quote_author TEXT,
  color TEXT DEFAULT 'blue',               -- quote card color: sun | blue | green | pink | purple | dark
  pinned BOOLEAN DEFAULT false,            -- pinned posts stay on top
  active BOOLEAN DEFAULT true,             -- false = hidden from customers
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS laundry_posts_branch_idx ON public.laundry_posts (branch_id, created_at DESC);

-- One like per customer per post
CREATE TABLE IF NOT EXISTS public.laundry_post_likes (
  post_id BIGINT REFERENCES public.laundry_posts(id) ON DELETE CASCADE,
  customer_id BIGINT REFERENCES public.laundry_customers(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (post_id, customer_id)
);

-- Move the old "Happy customers" photos into the feed (once)
INSERT INTO public.laundry_posts (branch_id, kind, tag, caption, image_ids, active, created_at)
SELECT h.branch_id, 'photo', 'customers', h.caption, ARRAY[h.image_id], h.active, h.created_at
FROM public.laundry_highlights h
WHERE NOT EXISTS (SELECT 1 FROM public.laundry_posts p WHERE p.tag = 'customers' AND p.image_ids = ARRAY[h.image_id]);

-- Public storage folder for videos (max 50 MB each). Uploads go through the server only.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('laundry-videos', 'laundry-videos', true, 52428800, ARRAY['video/mp4', 'video/quicktime', 'video/webm'])
ON CONFLICT (id) DO NOTHING;

-- Same setting as the other tables until the security lock (security-enable-rls.sql) is applied
ALTER TABLE public.laundry_posts      DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.laundry_post_likes DISABLE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload schema';
