-- S1p & Sp1n Laundry app: loyalty rewards (made by the owner in the POS) and the coffee menu switch.
-- Safe to run more than once.

-- Reward programs, e.g. "Every 25 kg → Free coffee + pastry"
CREATE TABLE IF NOT EXISTS public.laundry_reward_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id BIGINT REFERENCES public.branches_espresso(id),
  name TEXT NOT NULL,                          -- e.g. "Kilo Rewards"
  threshold_kg NUMERIC NOT NULL CHECK (threshold_kg > 0), -- every X kg
  reward_title TEXT NOT NULL,                  -- e.g. "Free coffee + pastry"
  reward_type TEXT NOT NULL DEFAULT 'item',    -- item | discount_amount | discount_percent
  reward_value NUMERIC DEFAULT 0,              -- ₱ off or % off (0 for free items)
  reward_note TEXT,                            -- conditions shown to customers
  count_from DATE,                             -- count kilos from this date (empty = from when the program was made)
  valid_days INT DEFAULT 60,                   -- voucher expires after this many days (empty = never)
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Vouchers earned by customers
CREATE TABLE IF NOT EXISTS public.laundry_rewards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES public.laundry_customers(id) ON DELETE CASCADE,
  program_id BIGINT REFERENCES public.laundry_reward_programs(id) ON DELETE SET NULL,
  code TEXT NOT NULL UNIQUE,                   -- shown to staff, e.g. SR-7K4P
  title TEXT NOT NULL,
  reward_type TEXT NOT NULL,
  reward_value NUMERIC DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'available',    -- available | redeemed
  earned_at TIMESTAMPTZ DEFAULT now(),
  expires_at TIMESTAMPTZ,
  redeemed_at TIMESTAMPTZ,
  redeemed_by TEXT
);
CREATE INDEX IF NOT EXISTS laundry_rewards_customer_idx ON public.laundry_rewards (customer_id, program_id);

-- Coffee menu: hidden ("Coming soon") for customers until switched on in the POS
ALTER TABLE public.laundry_app_settings ADD COLUMN IF NOT EXISTS coffee_menu_live BOOLEAN DEFAULT false;

-- Same setting as the other tables until the security lock (security-enable-rls.sql) is applied
ALTER TABLE public.laundry_reward_programs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.laundry_rewards         DISABLE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload schema';
