-- S1p & Sp1n Laundry app: push notifications.
-- Only creates laundry_* tables. Safe to run more than once.

-- Each phone that allowed notifications (one customer can have several phones)
CREATE TABLE IF NOT EXISTS public.laundry_push_tokens (
  token TEXT PRIMARY KEY,
  customer_id BIGINT REFERENCES public.laundry_customers(id) ON DELETE CASCADE,
  platform TEXT DEFAULT 'android',
  updated_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.laundry_push_tokens DISABLE ROW LEVEL SECURITY;

-- Announcements sent from the POS (Laundry App → Notifications)
CREATE TABLE IF NOT EXISTS public.laundry_announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id BIGINT REFERENCES public.branches_espresso(id),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  audience TEXT NOT NULL DEFAULT 'all',   -- all | inactive
  recipients INT DEFAULT 0,               -- customers targeted
  delivered INT DEFAULT 0,                -- phones that received it
  sent_by TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.laundry_announcements DISABLE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload schema';
