-- S1p & Sp1n Laundry app: promo slides, customer highlight photos, and the pictures they use.
-- Managed from the POS: Laundry App → Promotions. Safe to run more than once.

-- Pictures (stored small: the POS shrinks them before upload)
CREATE TABLE IF NOT EXISTS public.laundry_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mime TEXT NOT NULL DEFAULT 'image/jpeg',
  data TEXT NOT NULL,                 -- base64
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Promo slides on the app's Home screen
CREATE TABLE IF NOT EXISTS public.laundry_promos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id BIGINT REFERENCES public.branches_espresso(id),
  title TEXT NOT NULL,
  body TEXT,
  color TEXT DEFAULT 'sun',           -- sun | blue | green | pink | purple | dark
  image_id BIGINT REFERENCES public.laundry_media(id) ON DELETE SET NULL,
  starts_on DATE,                     -- empty = show now
  ends_on DATE,                       -- empty = no end
  sort INT DEFAULT 0,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Customer highlight photos
CREATE TABLE IF NOT EXISTS public.laundry_highlights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id BIGINT REFERENCES public.branches_espresso(id),
  image_id BIGINT NOT NULL REFERENCES public.laundry_media(id) ON DELETE CASCADE,
  caption TEXT,
  sort INT DEFAULT 0,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Same setting as the other tables until the security lock (security-enable-rls.sql) is applied
ALTER TABLE public.laundry_media      DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.laundry_promos     DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.laundry_highlights DISABLE ROW LEVEL SECURITY;

-- Start with the current 5+2 promo as the first slide
INSERT INTO public.laundry_promos (branch_id, title, body, color, sort)
SELECT 27, '5 + 2 kilo promo', 'Regular clothes, towels & bedsheets: 7 kg and up, 2 kg are free.', 'sun', 0
WHERE NOT EXISTS (SELECT 1 FROM public.laundry_promos WHERE branch_id = 27);

NOTIFY pgrst, 'reload schema';
