-- SQL Migration: BIR Compliance Enhancements
-- Run this in the Supabase SQL Editor

-- 1. Enhance branches to allow toggling BIR compliance mode per branch
ALTER TABLE public.branches
ADD COLUMN IF NOT EXISTS is_bir_compliant BOOLEAN DEFAULT FALSE;

-- 2. Enhance order_items for granular discounts and mixed transactions
ALTER TABLE public.order_items 
ADD COLUMN IF NOT EXISTS discount_id BIGINT REFERENCES public.discounts(id),
ADD COLUMN IF NOT EXISTS discount_amount REAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_vat_exempt BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS order_type TEXT DEFAULT 'dine-in'; -- for mixed transactions

-- 2. Enhance orders for reprint tracking and training mode
ALTER TABLE public.orders 
ADD COLUMN IF NOT EXISTS reprint_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_reprinted_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS is_training_mode BOOLEAN DEFAULT FALSE;

-- 3. Create Store Credits table
CREATE TABLE IF NOT EXISTS public.store_credits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id) DEFAULT 1,
    amount REAL NOT NULL,
    status TEXT DEFAULT 'active', -- active, used, void
    issued_to TEXT,
    reference_order_id BIGINT REFERENCES public.orders(id),
    used_on_order_id BIGINT REFERENCES public.orders(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Grand Accumulating Total (GAT) table
-- This must never be reset and should hold at least 12 digits. 
-- Using NUMERIC(20, 2) to ensure it can hold very large numbers accurately.
CREATE TABLE IF NOT EXISTS public.grand_accumulating_total (
    branch_id BIGINT PRIMARY KEY REFERENCES public.branches(id),
    total_sales NUMERIC(20, 2) NOT NULL DEFAULT 0.00,
    total_receipts BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Initialize GAT for branch 1 if it doesn't exist
INSERT INTO public.grand_accumulating_total (branch_id, total_sales, total_receipts)
VALUES (1, 0.00, 0)
ON CONFLICT (branch_id) DO NOTHING;

-- 5. Create Z-Readings table
CREATE TABLE IF NOT EXISTS public.z_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id) DEFAULT 1,
    z_counter BIGINT NOT NULL, -- Sequential Z-Reading number
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    generated_by TEXT,
    -- Sales Data
    gross_sales NUMERIC(20, 2) DEFAULT 0.00,
    net_sales NUMERIC(20, 2) DEFAULT 0.00,
    vat_amount NUMERIC(20, 2) DEFAULT 0.00,
    vat_exempt_sales NUMERIC(20, 2) DEFAULT 0.00,
    discount_total NUMERIC(20, 2) DEFAULT 0.00,
    service_charge_total NUMERIC(20, 2) DEFAULT 0.00,
    -- Payment Breakdowns
    cash_total NUMERIC(20, 2) DEFAULT 0.00,
    non_cash_total NUMERIC(20, 2) DEFAULT 0.00,
    void_total NUMERIC(20, 2) DEFAULT 0.00,
    -- Audit Data
    receipt_start_no BIGINT,
    receipt_end_no BIGINT,
    old_grand_total NUMERIC(20, 2) DEFAULT 0.00,
    new_grand_total NUMERIC(20, 2) DEFAULT 0.00
);

-- Ensure z_counter is unique per branch
ALTER TABLE public.z_readings ADD CONSTRAINT unique_z_counter_per_branch UNIQUE (branch_id, z_counter);
