-- SQL Migration: Create product_recipes table for BOM ingredient/supply tracking
-- Run this query in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

CREATE TABLE IF NOT EXISTS public.product_recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products_espresso(id) ON DELETE CASCADE,
    ingredient_id BIGINT REFERENCES public.products_espresso(id) ON DELETE CASCADE,
    quantity REAL NOT NULL DEFAULT 1,
    CONSTRAINT unique_product_ingredient UNIQUE(product_id, ingredient_id)
);
