-- Combined SQL Initialization Script for Espresso Yourself & Tea House
-- Copy and paste this into the Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. CREATE CORE TABLES IN SEQUENCE (DEPENDENCIES FIRST)

CREATE TABLE IF NOT EXISTS public.branches_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    is_bir_compliant BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS public.categories_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.discounts_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    value REAL NOT NULL,
    is_active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.business_settings_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT DEFAULT 'Espresso Yourself & Tea House',
    tin TEXT DEFAULT '770916958-00001',
    address TEXT DEFAULT 'SPACE NO. G301 A317 LEVEL 3 AYALA CENTER CEBU CEBU BUSINESS PARK LUZ CEBU CITY CAPITAL CEBU',
    permit_number TEXT DEFAULT 'FP032024-081-0438721-00001',
    ptu_date TEXT DEFAULT '04-11-2024',
    pos_sn TEXT DEFAULT '1000092480013',
    min TEXT DEFAULT '24032217031419869',
    business_style TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.users_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches_espresso(id),
    username TEXT NOT NULL UNIQUE,
    email TEXT,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'cashier', -- 'admin', 'manager', 'cashier'
    full_name TEXT,
    permissions JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.products_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches_espresso(id),
    category_id BIGINT REFERENCES public.categories_espresso(id),
    name TEXT NOT NULL,
    price REAL NOT NULL,
    cost REAL NOT NULL DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.tables_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches_espresso(id),
    name TEXT NOT NULL,
    capacity INTEGER DEFAULT 4,
    status TEXT DEFAULT 'available'
);

CREATE TABLE IF NOT EXISTS public.orders_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches_espresso(id),
    table_id BIGINT REFERENCES public.tables_espresso(id),
    order_type TEXT DEFAULT 'dine-in',
    status TEXT DEFAULT 'open',
    subtotal REAL DEFAULT 0,
    discount_id BIGINT REFERENCES public.discounts_espresso(id),
    discount_amount REAL DEFAULT 0,
    tax_amount REAL DEFAULT 0,
    service_charge REAL DEFAULT 0,
    total REAL DEFAULT 0,
    payment_method TEXT,
    amount_tendered REAL,
    change REAL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Additional columns from migrations
    receipt_number BIGINT,
    discount_customer_name TEXT,
    discount_customer_id_no TEXT,
    discount_customer_tin TEXT,
    discount_child_name TEXT,
    discount_child_birthdate TEXT,
    discount_child_age INTEGER,
    reprint_count INTEGER DEFAULT 0,
    last_reprinted_at TIMESTAMPTZ,
    is_training_mode BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS public.order_items_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders_espresso(id),
    product_id BIGINT REFERENCES public.products_espresso(id),
    quantity INTEGER NOT NULL,
    price REAL NOT NULL,
    status TEXT DEFAULT 'ordered',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Additional columns from migrations
    discount_id BIGINT REFERENCES public.discounts_espresso(id),
    discount_amount REAL DEFAULT 0,
    is_vat_exempt BOOLEAN DEFAULT FALSE,
    order_type TEXT DEFAULT 'dine-in'
);

CREATE TABLE IF NOT EXISTS public.shifts_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users_espresso(id),
    branch_id BIGINT REFERENCES public.branches_espresso(id),
    time_in TIMESTAMPTZ DEFAULT NOW(),
    time_out TIMESTAMPTZ,
    cash_in REAL NOT NULL,
    cash_out REAL,
    total_sales REAL DEFAULT 0,
    status TEXT DEFAULT 'open', -- 'open', 'closed'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.inventory_transactions_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products_espresso(id),
    type TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.pos_terminals_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches_espresso(id),
    name TEXT NOT NULL,
    status TEXT DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS public.voucher_items_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products_espresso(id),
    points_required INTEGER NOT NULL,
    new_price REAL NOT NULL DEFAULT 0,
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.voucher_redemptions_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches_espresso(id),
    order_id BIGINT REFERENCES public.orders_espresso(id),
    product_id BIGINT REFERENCES public.products_espresso(id),
    quantity INTEGER DEFAULT 1,
    points_used INTEGER NOT NULL,
    price REAL NOT NULL DEFAULT 0,
    reference_number TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.receipt_counter_espresso (
    id SERIAL PRIMARY KEY,
    branch_id BIGINT DEFAULT 1,
    current_value BIGINT NOT NULL DEFAULT 0,
    UNIQUE(branch_id)
);

CREATE TABLE IF NOT EXISTS public.store_credits_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches_espresso(id) DEFAULT 1,
    amount REAL NOT NULL,
    status TEXT DEFAULT 'active', -- active, used, void
    issued_to TEXT,
    reference_order_id BIGINT REFERENCES public.orders_espresso(id),
    used_on_order_id BIGINT REFERENCES public.orders_espresso(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.grand_accumulating_total_espresso (
    branch_id BIGINT PRIMARY KEY REFERENCES public.branches_espresso(id),
    total_sales NUMERIC(20, 2) NOT NULL DEFAULT 0.00,
    total_receipts BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.z_readings_espresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches_espresso(id) DEFAULT 1,
    z_counter BIGINT NOT NULL, -- Sequential Z-Reading number
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    generated_by TEXT,
    gross_sales NUMERIC(20, 2) DEFAULT 0.00,
    net_sales NUMERIC(20, 2) DEFAULT 0.00,
    vat_amount NUMERIC(20, 2) DEFAULT 0.00,
    vat_exempt_sales NUMERIC(20, 2) DEFAULT 0.00,
    discount_total NUMERIC(20, 2) DEFAULT 0.00,
    service_charge_total NUMERIC(20, 2) DEFAULT 0.00,
    cash_total NUMERIC(20, 2) DEFAULT 0.00,
    non_cash_total NUMERIC(20, 2) DEFAULT 0.00,
    void_total NUMERIC(20, 2) DEFAULT 0.00,
    receipt_start_no BIGINT,
    receipt_end_no BIGINT,
    old_grand_total NUMERIC(20, 2) DEFAULT 0.00,
    new_grand_total NUMERIC(20, 2) DEFAULT 0.00,
    CONSTRAINT unique_z_counter_per_branch UNIQUE (branch_id, z_counter)
);


-- 2. SEED INITIAL COFFEE SHOP DEMO DATA

-- Branches
INSERT INTO public.branches_espresso (name, address, is_bir_compliant) VALUES
('Main Branch', '123 Main St', TRUE),
('Mall Branch', '456 Mall Ave', FALSE)
ON CONFLICT DO NOTHING;

-- Categories
INSERT INTO public.categories_espresso (name) VALUES
('Hot Coffee'), ('Iced & Blended'), ('Tea & Alternatives'), ('Pastries & Desserts')
ON CONFLICT DO NOTHING;

-- Products
INSERT INTO public.products_espresso (branch_id, category_id, name, price, cost, stock) VALUES
-- Branch 1 (Main) Hot Coffee
(1, 1, 'Espresso (Double)', 100, 30, 99),
(1, 1, 'Americano', 120, 25, 150),
(1, 1, 'Cafe Latte', 140, 45, 100),
(1, 1, 'Cappuccino', 140, 45, 80),
(1, 1, 'Spanish Latte', 150, 50, 100),
-- Branch 1 (Main) Iced & Blended
(1, 2, 'Iced Caramel Macchiato', 160, 55, 120),
(1, 2, 'Iced Spanish Latte', 160, 55, 150),
(1, 2, 'Mocha Frappe', 170, 60, 80),
-- Branch 1 (Main) Tea & Alternatives
(1, 3, 'Matcha Latte', 150, 50, 100),
(1, 3, 'Iced Peach Tea', 110, 25, 200),
(1, 3, 'Hot Earl Grey', 100, 15, 150),
-- Branch 1 (Main) Pastries
(1, 4, 'Butter Croissant', 95, 40, 40),
(1, 4, 'Chocolate Chip Cookie', 80, 30, 60),
(1, 4, 'Blueberry Cheesecake', 180, 80, 25),

-- Branch 2 (Mall) Seeds
(2, 1, 'Americano', 130, 25, 100),
(2, 1, 'Cafe Latte', 150, 45, 80),
(2, 2, 'Iced Caramel Macchiato', 170, 55, 90),
(2, 4, 'Butter Croissant', 105, 40, 30)
ON CONFLICT DO NOTHING;

-- Tables
INSERT INTO public.tables_espresso (branch_id, name, capacity) VALUES
(1, 'Table 1', 4),
(1, 'Table 2', 4),
(1, 'Table 3', 4),
(1, 'Table 4', 4),
(1, 'Table 5', 4),
(2, 'Table A', 2),
(2, 'Table B', 2),
(2, 'Table C', 2)
ON CONFLICT DO NOTHING;

-- Discounts
INSERT INTO public.discounts_espresso (name, type, value) VALUES
('Senior Citizen (20% + VAT Exempt)', 'percentage', 20),
('PWD (20% + VAT Exempt)', 'percentage', 20),
('National Athlete (20%)', 'percentage', 20),
('Employee (10%)', 'percentage', 10)
ON CONFLICT DO NOTHING;

-- Default Admin User
INSERT INTO public.users_espresso (branch_id, username, email, password, role, full_name, permissions) 
VALUES (1, 'admin', 'junrel@allsetdigital.com', 'admin123', 'admin', 'Junrel Ejurango', 
'{"/": "admin", "/pos": "admin", "/orders": "admin", "/kitchen": "admin", "/tables": "admin", "/inventory": "admin", "/vouchers": "admin", "/reports": "admin", "/settings": "admin"}'::jsonb)
ON CONFLICT (username) DO NOTHING;

-- Business Settings
INSERT INTO public.business_settings_espresso (id, company_name) 
VALUES (1, 'Espresso Yourself & Tea House') 
ON CONFLICT (id) DO NOTHING;

-- Grand Accumulating Total (GAT) Seed
INSERT INTO public.grand_accumulating_total_espresso (branch_id, total_sales, total_receipts)
VALUES (1, 0.00, 0), (2, 0.00, 0)
ON CONFLICT (branch_id) DO NOTHING;

-- Receipt Counter Seed
INSERT INTO public.receipt_counter_espresso (branch_id, current_value)
VALUES (1, 795), (2, 0)
ON CONFLICT (branch_id) DO NOTHING;


-- Disable Row-Level Security (RLS) on all Espresso Yourself & Tea House tables.
ALTER TABLE public.branches_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tables_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.discounts_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_transactions_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_terminals_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.voucher_items_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.voucher_redemptions_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.shifts_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipt_counter_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_settings_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_credits_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.grand_accumulating_total_espresso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.z_readings_espresso DISABLE ROW LEVEL SECURITY;

-- 1. Insert Branches
INSERT INTO public.branches_espresso (name, address, is_bir_compliant) VALUES
('Main Branch', '123 Main St', TRUE),
('Mall Branch', '456 Mall Ave', FALSE)
ON CONFLICT DO NOTHING;

-- 2. Insert Categories
INSERT INTO public.categories_espresso (name) VALUES
('Hot Coffee'), ('Iced & Blended'), ('Tea & Alternatives'), ('Pastries & Desserts')
ON CONFLICT DO NOTHING;

-- 3. Insert Products
INSERT INTO public.products_espresso (branch_id, category_id, name, price, cost, stock) VALUES
-- Branch 1 (Main) Hot Coffee
(1, 1, 'Espresso (Double)', 100, 30, 99),
(1, 1, 'Americano', 120, 25, 150),
(1, 1, 'Cafe Latte', 140, 45, 100),
(1, 1, 'Cappuccino', 140, 45, 80),
(1, 1, 'Spanish Latte', 150, 50, 100),
-- Branch 1 (Main) Iced & Blended
(1, 2, 'Iced Caramel Macchiato', 160, 55, 120),
(1, 2, 'Iced Spanish Latte', 160, 55, 150),
(1, 2, 'Mocha Frappe', 170, 60, 80),
-- Branch 1 (Main) Tea & Alternatives
(1, 3, 'Matcha Latte', 150, 50, 100),
(1, 3, 'Iced Peach Tea', 110, 25, 200),
(1, 3, 'Hot Earl Grey', 100, 15, 150),
-- Branch 1 (Main) Pastries
(1, 4, 'Butter Croissant', 95, 40, 40),
(1, 4, 'Chocolate Chip Cookie', 80, 30, 60),
(1, 4, 'Blueberry Cheesecake', 180, 80, 25),

-- Branch 2 (Mall) Seeds
(2, 1, 'Americano', 130, 25, 100),
(2, 1, 'Cafe Latte', 150, 45, 80),
(2, 2, 'Iced Caramel Macchiato', 170, 55, 90),
(2, 4, 'Butter Croissant', 105, 40, 30)
ON CONFLICT DO NOTHING;

-- 4. Insert Tables
INSERT INTO public.tables_espresso (branch_id, name, capacity) VALUES
(1, 'Table 1', 4),
(1, 'Table 2', 4),
(1, 'Table 3', 4),
(1, 'Table 4', 4),
(1, 'Table 5', 4),
(2, 'Table A', 2),
(2, 'Table B', 2),
(2, 'Table C', 2)
ON CONFLICT DO NOTHING;

-- 5. Insert Discounts
INSERT INTO public.discounts_espresso (name, type, value) VALUES
('Senior Citizen (20% + VAT Exempt)', 'percentage', 20),
('PWD (20% + VAT Exempt)', 'percentage', 20),
('National Athlete (20%)', 'percentage', 20),
('Employee (10%)', 'percentage', 10)
ON CONFLICT DO NOTHING;

-- 6. Insert Default Admin User
INSERT INTO public.users_espresso (branch_id, username, email, password, role, full_name, permissions) 
VALUES (1, 'admin', 'junrel@allsetdigital.com', 'admin123', 'admin', 'Junrel Ejurango', 
'{"/": "admin", "/pos": "admin", "/orders": "admin", "/kitchen": "admin", "/tables": "admin", "/inventory": "admin", "/vouchers": "admin", "/reports": "admin", "/settings": "admin"}'::jsonb)
ON CONFLICT (username) DO NOTHING;

-- 7. Insert Business Settings
INSERT INTO public.business_settings_espresso (id, company_name) 
VALUES (1, 'Espresso Yourself & Tea House') 
ON CONFLICT (id) DO NOTHING;

-- 8. Insert Grand Accumulating Total (GAT) Seed
INSERT INTO public.grand_accumulating_total_espresso (branch_id, total_sales, total_receipts)
VALUES (1, 0.00, 0), (2, 0.00, 0)
ON CONFLICT (branch_id) DO NOTHING;

-- 9. Insert Receipt Counter Seed
INSERT INTO public.receipt_counter_espresso (branch_id, current_value)
VALUES (1, 795), (2, 0)
ON CONFLICT (branch_id) DO NOTHING;
