-- Run this in your Supabase SQL Editor to add the users table

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id),
    username TEXT NOT NULL UNIQUE,
    email TEXT,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'cashier', -- 'admin', 'manager', 'cashier'
    full_name TEXT,
    permissions JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_active INTEGER DEFAULT 1
);

-- Default admin user
INSERT INTO public.users (branch_id, username, email, password, role, full_name) 
VALUES (1, 'admin', 'junrel@allsetdigital.com', 'admin123', 'admin', 'Junrel Ejurango')
ON CONFLICT (username) DO NOTHING;
