-- Run this in your Supabase SQL Editor to add the shifts table

CREATE TABLE IF NOT EXISTS public.shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id),
    branch_id BIGINT REFERENCES public.branches(id),
    time_in TIMESTAMPTZ DEFAULT NOW(),
    time_out TIMESTAMPTZ,
    cash_in REAL NOT NULL,
    cash_out REAL,
    total_sales REAL DEFAULT 0,
    status TEXT DEFAULT 'open', -- 'open', 'closed'
    created_at TIMESTAMPTZ DEFAULT NOW()
);
