-- Copy and paste this into the Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

CREATE TABLE IF NOT EXISTS public.branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT
);

CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id),
    category_id BIGINT REFERENCES public.categories(id),
    name TEXT NOT NULL,
    price REAL NOT NULL,
    cost REAL NOT NULL DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id),
    name TEXT NOT NULL,
    capacity INTEGER DEFAULT 4,
    status TEXT DEFAULT 'available'
);

CREATE TABLE IF NOT EXISTS public.discounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    value REAL NOT NULL,
    is_active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id),
    table_id BIGINT REFERENCES public.tables(id),
    order_type TEXT DEFAULT 'dine-in',
    status TEXT DEFAULT 'open',
    subtotal REAL DEFAULT 0,
    discount_id BIGINT REFERENCES public.discounts(id),
    discount_amount REAL DEFAULT 0,
    tax_amount REAL DEFAULT 0,
    service_charge REAL DEFAULT 0,
    total REAL DEFAULT 0,
    payment_method TEXT,
    amount_tendered REAL,
    change REAL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id),
    product_id BIGINT REFERENCES public.products(id),
    quantity INTEGER NOT NULL,
    price REAL NOT NULL,
    status TEXT DEFAULT 'ordered',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.inventory_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id),
    type TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.pos_terminals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id),
    name TEXT NOT NULL,
    status TEXT DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS public.voucher_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id),
    points_required INTEGER NOT NULL,
    new_price REAL NOT NULL DEFAULT 0,
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.voucher_redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id),
    order_id BIGINT REFERENCES public.orders(id),
    product_id BIGINT REFERENCES public.products(id),
    quantity INTEGER DEFAULT 1,
    points_used INTEGER NOT NULL,
    price REAL NOT NULL DEFAULT 0,
    reference_number TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Data (Optional, run if you want the initial demo data)
INSERT INTO public.branches (name, address) VALUES
('Main Branch', '123 Main St'),
('Mall Branch', '456 Mall Ave');

INSERT INTO public.categories (name) VALUES
('Mains'), ('Drinks'), ('Desserts'), ('Appetizers');

INSERT INTO public.products (branch_id, category_id, name, price, cost, stock) VALUES
(1, 1, 'Adobo', 150, 80, 50),
(1, 1, 'Sinigang', 200, 100, 40),
(1, 2, 'Mango Shake', 80, 30, 100),
(1, 2, 'Iced Tea', 50, 15, 200),
(1, 3, 'Leche Flan', 60, 25, 30),
(1, 4, 'Lumpia', 120, 60, 80),
(2, 1, 'Adobo', 160, 80, 50),
(2, 2, 'Iced Tea', 60, 15, 200);

INSERT INTO public.tables (branch_id, name, capacity) VALUES
(1, 'Table 1', 4),
(1, 'Table 2', 4),
(1, 'Table 3', 4),
(1, 'Table 4', 4),
(1, 'Table 5', 4),
(2, 'Table A', 2),
(2, 'Table B', 2),
(2, 'Table C', 2);

INSERT INTO public.discounts (name, type, value) VALUES
('Senior Citizen (20% + VAT Exempt)', 'percentage', 20),
('PWD (20% + VAT Exempt)', 'percentage', 20),
('National Athlete (20%)', 'percentage', 20),
('Employee (10%)', 'percentage', 10);
